### ISSUE TITLE
Sprint 2 Schedule

### ISSUE THREAD

**Issue by oturnermajor** [oturnermajor/playground#27]
### August
- [ ] 22nd - Integrate Google Analytics (#15)
- [ ] 23-24th - Messaging Conversation Page (#16)
- [ ] 25-26th - Messaging Dashboard page (#14)
- [ ] 29-31st - Booking/Payments (#17)
- [ ] 1-2nd September - Bug fixes, testing, catch-up
